from pathlib import Path
from typing import Dict, Any, Optional
import argparse
import json
import time

import joblib
import numpy as np
from scipy import sparse
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import roc_auc_score, log_loss, accuracy_score


# ============================================================
# Logging helpers
# ============================================================

def log(msg: str) -> None:
    print(msg, flush=True)


def log_step(step_no: int, total_steps: int, title: str) -> None:
    log("\n" + "=" * 80)
    log(f"[Step {step_no}/{total_steps}] {title}")
    log("=" * 80)


def log_sub(msg: str) -> None:
    log(f"  -> {msg}")


# ============================================================
# Data loading
# ============================================================

def load_processed_dataset(processed_dir: Path) -> Dict[str, Any]:
    """
    Load processed dataset generated by preprocess.py
    """
    if not processed_dir.exists():
        raise FileNotFoundError(f"Processed directory not found: {processed_dir}")

    required_files = [
        "X_train.npz",
        "X_test.npz",
        "y_train.npy",
        "y_test.npy",
        "w_baseline_train.npy",
        "w_baseline_test.npy",
        "w_ips_train.npy",
        "w_ips_test.npy",
        "w_snips_train.npy",
        "w_snips_test.npy",
        "feature_names.csv",
        "metadata.json",
    ]
    for fname in required_files:
        fpath = processed_dir / fname
        if not fpath.exists():
            raise FileNotFoundError(f"Required file missing: {fpath}")

    log_sub(f"Loading processed data from: {processed_dir}")

    X_train = sparse.load_npz(processed_dir / "X_train.npz").tocsr()
    X_test = sparse.load_npz(processed_dir / "X_test.npz").tocsr()

    y_train = np.load(processed_dir / "y_train.npy")
    y_test = np.load(processed_dir / "y_test.npy")

    w_baseline_train = np.load(processed_dir / "w_baseline_train.npy")
    w_baseline_test = np.load(processed_dir / "w_baseline_test.npy")

    w_ips_train = np.load(processed_dir / "w_ips_train.npy")
    w_ips_test = np.load(processed_dir / "w_ips_test.npy")

    w_snips_train = np.load(processed_dir / "w_snips_train.npy")
    w_snips_test = np.load(processed_dir / "w_snips_test.npy")

    with open(processed_dir / "metadata.json", "r", encoding="utf-8") as f:
        metadata = json.load(f)

    log_sub(f"X_train shape = {X_train.shape}")
    log_sub(f"X_test shape  = {X_test.shape}")
    log_sub(f"y_train shape = {y_train.shape}")
    log_sub(f"y_test shape  = {y_test.shape}")

    return {
        "X_train": X_train,
        "X_test": X_test,
        "y_train": y_train,
        "y_test": y_test,
        "w_baseline_train": w_baseline_train,
        "w_baseline_test": w_baseline_test,
        "w_ips_train": w_ips_train,
        "w_ips_test": w_ips_test,
        "w_snips_train": w_snips_train,
        "w_snips_test": w_snips_test,
        "metadata": metadata,
    }


# ============================================================
# Model training
# ============================================================

def train_sgd_logistic_with_progress(
    X_train,
    y_train,
    sample_weight: Optional[np.ndarray],
    model_name: str,
    n_epochs: int = 3,
    batch_size: int = 100_000,
    alpha: float = 1e-5,
    random_state: int = 42,
    positive_class_weight: float = 1.0,
    sample_weight_clip_max: Optional[float] = None,
) -> SGDClassifier:
    """
    Train a large-scale sparse logistic model using SGDClassifier + partial_fit.

    Why this model?
    - Suitable for very large sparse matrices
    - Much lighter than full LogisticRegression on huge OBD data
    - Supports sample_weight, which is exactly what we need for IPS / SNIPS
    """

    n_samples = X_train.shape[0]
    n_batches = int(np.ceil(n_samples / batch_size))

    log_sub(f"Model          : {model_name}")
    log_sub(f"Training rows  : {n_samples}")
    log_sub(f"Feature dim    : {X_train.shape[1]}")
    log_sub(f"Epochs         : {n_epochs}")
    log_sub(f"Batch size     : {batch_size}")
    log_sub(f"Batches/epoch  : {n_batches}")
    log_sub(f"Alpha          : {alpha}")
    log_sub(f"Positive class weight : {positive_class_weight}")
    log_sub(f"Sample weight clip max: {sample_weight_clip_max}")

    model = SGDClassifier(
        loss="log_loss",
        penalty="l2",
        alpha=1e-4,
        fit_intercept=True,
        max_iter=1,
        tol=None,
        shuffle=False,
        random_state=random_state,
        learning_rate="constant",
        eta0=0.001,
        average=True,
        class_weight={0:1.0, 1:positive_class_weight},
    )

    classes = np.array([0, 1], dtype=np.int32)

    train_start = time.time()

    for epoch in range(n_epochs):
        epoch_start = time.time()

        log_sub(f"Starting epoch {epoch + 1}/{n_epochs}")

        rng = np.random.default_rng(seed=random_state + epoch)
        indices = rng.permutation(n_samples)

        for batch_idx in range(n_batches):
            start = batch_idx * batch_size
            end = min((batch_idx + 1) * batch_size, n_samples)
            batch_indices = indices[start:end]

            X_batch = X_train[batch_indices]
            y_batch = y_train[batch_indices].astype(np.int32)

            if sample_weight is None:
                sw_batch = None
            else:
                sw_batch = sample_weight[batch_indices].astype(np.float32)

                if sample_weight_clip_max is not None:
                    sw_batch = np.clip(sw_batch, 0.0, sample_weight_clip_max)

            if epoch == 0 and batch_idx == 0:
                model.partial_fit(
                    X_batch,
                    y_batch,
                    classes=classes,
                    sample_weight=sw_batch,
                )
            else:
                model.partial_fit(
                    X_batch,
                    y_batch,
                    sample_weight=sw_batch,
                )

            # progress print every 10 batches or last batch
            if (batch_idx + 1) % 10 == 0 or (batch_idx + 1) == n_batches:
                processed = end
                pct = processed / n_samples * 100
                elapsed = time.time() - epoch_start

                if sw_batch is None:
                    weight_msg = "sw=None"
                else:
                    weight_msg = (
                        f"sw_mean={np.mean(sw_batch):.3f}, "
                        f"sw_max={np.max(sw_batch):.3f}"
                    )

                log_sub(
                    f"Epoch {epoch + 1}/{n_epochs} | "
                    f"Batch {batch_idx + 1}/{n_batches} | "
                    f"Processed {processed}/{n_samples} ({pct:.2f}%) | "
                    f"Elapsed {elapsed:.1f}s | "
                    f"{weight_msg}"
                )

        log_sub(
            f"Finished epoch {epoch + 1}/{n_epochs} in {time.time() - epoch_start:.1f}s"
        )

    total_elapsed = time.time() - train_start
    log_sub(f"Finished training [{model_name}] in {total_elapsed:.1f}s")

    return model


# ============================================================
# Prediction helpers
# ============================================================

def predict_proba_in_batches(
    model: SGDClassifier,
    X,
    batch_size: int = 200_000,
) -> np.ndarray:
    """
    Predict positive-class probabilities in batches to avoid memory spikes.
    """
    n_samples = X.shape[0]
    probs = np.empty(n_samples, dtype=np.float32)

    n_batches = int(np.ceil(n_samples / batch_size))
    pred_start = time.time()

    for batch_idx in range(n_batches):
        start = batch_idx * batch_size
        end = min((batch_idx + 1) * batch_size, n_samples)

        probs[start:end] = model.predict_proba(X[start:end])[:, 1].astype(np.float32)

        if (batch_idx + 1) % 10 == 0 or (batch_idx + 1) == n_batches:
            pct = end / n_samples * 100
            elapsed = time.time() - pred_start
            log_sub(
                f"Prediction batch {batch_idx + 1}/{n_batches} | "
                f"Processed {end}/{n_samples} ({pct:.2f}%) | "
                f"Elapsed {elapsed:.1f}s"
            )

    return probs


def compute_basic_metrics(y_true: np.ndarray, y_prob: np.ndarray) -> Dict[str, float]:
    """
    Basic sanity-check metrics.
    These are NOT the final OPE evaluation metrics.
    They are only to ensure training worked.
    """
    y_pred = (y_prob >= 0.5).astype(np.int32)

    metrics = {
        "auc": float(roc_auc_score(y_true, y_prob)),
        "log_loss": float(log_loss(y_true, y_prob, labels=[0, 1])),
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "mean_pred_prob": float(np.mean(y_prob)),
        "positive_rate_true": float(np.mean(y_true)),
    }
    return metrics


# ============================================================
# Training wrapper for one model
# ============================================================

def train_and_save_single_model(
    model_name: str,
    X_train,
    y_train,
    X_test,
    y_test,
    train_weight: Optional[np.ndarray],
    test_weight: Optional[np.ndarray],
    output_dir: Path,
    n_epochs: int,
    batch_size: int,
    alpha: float,
    random_state: int,
    positive_class_weight: float,
    sample_weight_clip_max: Optional[float],
) -> Dict[str, Any]:
    """
    Train one model, save everything needed for stage 3 evaluation.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    log_step(3, 5, f"Training model = {model_name}")

    model = train_sgd_logistic_with_progress(
        X_train=X_train,
        y_train=y_train,
        sample_weight=train_weight,
        model_name=model_name,
        n_epochs=n_epochs,
        batch_size=batch_size,
        alpha=alpha,
        random_state=random_state,
        positive_class_weight=positive_class_weight,
        sample_weight_clip_max=sample_weight_clip_max,
    )

    # Save model
    model_path = output_dir / "model.joblib"
    joblib.dump(model, model_path)
    log_sub(f"Saved model -> {model_path}")

    # Predict on test set
    log_step(4, 5, f"Generating test predictions for model = {model_name}")
    y_prob_test = predict_proba_in_batches(model, X_test, batch_size=200_000)
    y_pred_test = (y_prob_test >= 0.5).astype(np.int32)

    np.save(output_dir / "y_prob_test.npy", y_prob_test)
    np.save(output_dir / "y_pred_test.npy", y_pred_test)
    log_sub("Saved y_prob_test.npy and y_pred_test.npy")

    # Basic metrics (sanity check only)
    log_step(5, 5, f"Computing sanity-check metrics for model = {model_name}")

    metrics = compute_basic_metrics(y_test, y_prob_test)

    # Save weighted test statistics too, for later reference
    if test_weight is not None:
        metrics["test_weight_mean"] = float(np.mean(test_weight))
        metrics["test_weight_min"] = float(np.min(test_weight))
        metrics["test_weight_max"] = float(np.max(test_weight))

    metrics_path = output_dir / "metrics.json"
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(metrics, f, ensure_ascii=False, indent=2)

    train_config = {
        "model_type": "SGDClassifier(log_loss)",
        "model_name": model_name,
        "n_epochs": n_epochs,
        "batch_size": batch_size,
        "alpha": alpha,
        "random_state": random_state,
        "weighting": model_name,
        "positive_class_weight": positive_class_weight,
        "sample_weight_clip_max": sample_weight_clip_max,
    }
    config_path = output_dir / "train_config.json"
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(train_config, f, ensure_ascii=False, indent=2)

    log_sub(f"Saved metrics -> {metrics_path}")
    log_sub(f"Saved config  -> {config_path}")
    log_sub(f"Metrics = {metrics}")

    return {
        "model": model,
        "y_prob_test": y_prob_test,
        "y_pred_test": y_pred_test,
        "metrics": metrics,
    }


# ============================================================
# Main
# ============================================================

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dataset",
        choices=["bts", "random"],
        default="bts",
        help="Which processed dataset to use for training.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=5,
        help="Number of training epochs for SGD.",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=100_000,
        help="Mini-batch size for SGD partial_fit.",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=1e-5,
        help="L2 regularization strength for SGDClassifier.",
    )
    parser.add_argument(
        "--random_state",
        type=int,
        default=42,
        help="Random seed.",
    )

    args = parser.parse_args()

    total_steps = 5

    script_path = Path(__file__).resolve()
    src_dir = script_path.parent
    project_root = src_dir.parent

    processed_dir = project_root / "outputs" / f"processed_{args.dataset}"
    model_root_dir = project_root / "outputs" / f"models_{args.dataset}"
    model_root_dir.mkdir(parents=True, exist_ok=True)

    log("\n" + "#" * 80)
    log("MODEL TRAINING STARTED")
    log("#" * 80)
    log(f"Project root   : {project_root}")
    log(f"Processed dir  : {processed_dir}")
    log(f"Model output   : {model_root_dir}")
    log(f"Dataset        : {args.dataset}")
    log(f"Epochs         : {args.epochs}")
    log(f"Batch size     : {args.batch_size}")
    log(f"Alpha          : {args.alpha}")
    log(f"Random state   : {args.random_state}")

    # --------------------------------------------------------
    # Step 1: Load processed dataset
    # --------------------------------------------------------
    log_step(1, total_steps, "Loading processed dataset")
    data = load_processed_dataset(processed_dir)

    X_train = data["X_train"]
    X_test = data["X_test"]
    y_train = data["y_train"]
    y_test = data["y_test"]

    log_sub(f"Train positive rate = {np.mean(y_train):.6f}")
    log_sub(f"Test positive rate  = {np.mean(y_test):.6f}")

    w_baseline_train = data["w_baseline_train"]
    w_baseline_test = data["w_baseline_test"]

    w_ips_train = data["w_ips_train"]
    w_ips_test = data["w_ips_test"]

    w_snips_train = data["w_snips_train"]
    w_snips_test = data["w_snips_test"]

    # --------------------------------------------------------
    # Step 2: Train all three models
    # --------------------------------------------------------
    log_step(2, total_steps, "Training three models: baseline / ips / snips")

    summary = {}

    # 1) Baseline
    baseline_dir = model_root_dir / "baseline"
    baseline_result = train_and_save_single_model(
        model_name="baseline",
        X_train=X_train,
        y_train=y_train,
        X_test=X_test,
        y_test=y_test,
        train_weight=w_baseline_train,
        test_weight=w_baseline_test,
        output_dir=baseline_dir,
        n_epochs=args.epochs,
        batch_size=args.batch_size,
        alpha=args.alpha,
        random_state=args.random_state,
        positive_class_weight=200.0,
        sample_weight_clip_max=None,
    )
    summary["baseline"] = baseline_result["metrics"]

    # 2) IPS
    ips_dir = model_root_dir / "ips"
    ips_result = train_and_save_single_model(
        model_name="ips",
        X_train=X_train,
        y_train=y_train,
        X_test=X_test,
        y_test=y_test,
        train_weight=w_ips_train,
        test_weight=w_ips_test,
        output_dir=ips_dir,
        n_epochs=args.epochs,
        batch_size=args.batch_size,
        alpha=args.alpha,
        random_state=args.random_state,
        positive_class_weight=1.0,
        sample_weight_clip_max=50.0,
    )
    summary["ips"] = ips_result["metrics"]

    # 3) SNIPS
    snips_dir = model_root_dir / "snips"
    snips_result = train_and_save_single_model(
        model_name="snips",
        X_train=X_train,
        y_train=y_train,
        X_test=X_test,
        y_test=y_test,
        train_weight=w_snips_train,
        test_weight=w_snips_test,
        output_dir=snips_dir,
        n_epochs=args.epochs,
        batch_size=args.batch_size,
        alpha=args.alpha,
        random_state=args.random_state,
        positive_class_weight=1.0,
        sample_weight_clip_max=50.0,
    )
    summary["snips"] = snips_result["metrics"]

    # Save summary
    summary_path = model_root_dir / "training_summary.json"
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    log("\n" + "#" * 80)
    log("MODEL TRAINING FINISHED")
    log("#" * 80)
    log(json.dumps(summary, indent=2, ensure_ascii=False))
    log(f"Saved summary -> {summary_path}")
    log("#" * 80 + "\n")


if __name__ == "__main__":
    main()